### ISSUE TITLE
the student mode (student_config_dir) of the second step general distillation

### ISSUE THREAD

**Issue by L-Maybe** [Yaozeng/TinyBERT#1]
Hi, i was wondering about the second step of the general distillation, how to add student model.  Is the code of 'student model' on github.

**Comment by Yaozeng** [comment]
> Hi, i was wondering about the second step of the general distillation, how to add student model. Is the code of 'student model' on github.

this repo is a copy of the original repo https://github.com/huawei-noah/Pretrained-Language-Model.git, except i revised code for reuse the feature.

**Comment by Yaozeng** [comment]
> Hi, i was wondering about the second step of the general distillation, how to add student model. Is the code of 'student model' on github.

student model is a less small bert, model defined in transformer/modeling.py,  refer paper https://arxiv.org/abs/1909.10351

**Comment by L-Maybe** [comment]
@Yaozeng Tanks for you reply, i'll try.
